### ISSUE TITLE
Unspecific 503 error on request()

### ISSUE THREAD

**Issue by arthosdevelops** [nats-io/nats.ts#114]
While calling the nc.request(msg, data, opts), we randomly face the following 503 error. Previously it would go away with a container restart, but it has been coming up quite often recently and I am not sure where to start debugging since the message is not very descriptive as to point to the root cause of this error. Is this a known error?

 ```NatsError: 503 
NatsError: 503
    at NatsError.errorForCode (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/error.js:100:16)
    at isRequestError (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/msg.js:29:42)
    at SubscriptionImpl.callback (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/nats.js:229:56)
    at ProtocolHandler.processMsg (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/protocol.js:346:17)
    at ProtocolHandler.push (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/protocol.js:446:22)
    at Parser.parse (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/parser.js:197:41)
    at ProtocolHandler.<anonymous> (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/protocol.js:189:45)
    at Generator.next (<anonymous>)
    at fulfilled (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/protocol.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Error
    at NatsConnectionImpl.request (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/nats.js:216:28)```

**Comment by aricart** [comment]
503 means there are no subscribers listening to the request subject.


This version of the nats client is superceded by the current nats.js.  You should consider upgrading.

**Comment by aricart** [comment]
Actually from the trace looks like you are on a recent release.  The repo here is for a different library

**Comment by arthosdevelops** [comment]
@aricart Yes, we are using the recent release. Is this the library you're referring to? https://github.com/nats-io/nats.deno/issues/342 
Created a issue there too
